-- Customer Lifetime Value (CLV) KPI Model
-- This model calculates the average revenue generated by a customer throughout their entire relationship with the company.

with paid_invoices as (
    select
        CUSTOMER_ID,
        TOTAL_AMOUNT
    from {{ source('Combined Source', 'BIL_INVOICES') }}
    where STATUS = 'Paid'
)

select
    sum(TOTAL_AMOUNT) / count(distinct CUSTOMER_ID) as CLV
from paid_invoices;
